name = "app"
version = "1.0.0"
description = "A web service for fetching open graph metadata"
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.30"
gleam_erlang = "~> 0.23"
mist = ">= 1.2.0 and < 2.0.0"
wisp = ">= 0.16.0 and < 1.0.0"
gleam_httpc = ">= 2.2.0 and < 3.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"


[dev-dependencies]
gleeunit = "~> 1.0"
